// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytfgkhconxytcansavzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0ZmdraGNvbnh5dGNhbnNhdnp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MzU2NjcsImV4cCI6MjA3NDAxMTY2N30.QBJnXNKW_pH_y4swPoHeEE-7GSJlKqZM_HQxGFforW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});